apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "float-manager-server.fullname" . }}-worker
  labels:
    {{- include "float-manager-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "float-manager-server.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "float-manager-server.labels" . | nindent 8 }}
        {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.worker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "float-manager-server.serviceAccountName" . }}
      {{- with .Values.worker.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.worker.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}@{{ .Values.worker.image.digest }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command:
            - deno
          args:
          - run
          - --allow-env
          - --env-file
          - --allow-net
          - --allow-read
          - src/main.ts
          -  start-worker
          {{- with .Values.worker.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- with .Values.worker.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.worker.kafka.tls.certSecretKey }}
            - name: kafka-cert-secret
              mountPath: /app/certs/fullchain.pem
              subPath: {{ .Values.worker.kafka.tls.certSecretKey }}
            {{- end }}
            {{- if .Values.worker.kafka.tls.keySecretKey }}
            - name: kafka-cert-secret
              mountPath: /app/certs/privkey.pem
              subPath: {{ .Values.worker.kafka.tls.keySecretKey }}
            {{- end }}
            {{- if .Values.worker.kafka.tls.ca.secretKey }}
            - name: kafka-ca-secret
              mountPath: /app/certs/ca.crt
              subPath: {{ .Values.worker.kafka.tls.ca.secretKey }}
            {{- end }}
          env:
          {{- if or .Values.database.password .Values.database.existingSecret -}}
            {{- include "float-manager-server.databaseUrl" . | nindent 12 }}
          {{- end }}
            - name: KAFKA_BROKERS
              value: {{ .Values.worker.kafka.brokers | join ";" }}
      volumes:
        {{- with .Values.worker.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.worker.kafka.tls.ca.secretName }}
        - name: kafka-ca-secret
          secret:
            secretName: {{ .Values.worker.kafka.tls.ca.secretName }}
        {{- end }}
        {{- if .Values.worker.kafka.tls.secretName }}
        - name: kafka-cert-secret
          secret:
            secretName: {{ .Values.worker.kafka.tls.secretName }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
